### ISSUE TITLE
Make "autofocus" an selectable property of input fields

### ISSUE THREAD

**Issue by christoph2806** [perak/kitchen-cli#25]
Currently, kitchen puts an "autofocus" attribute in the first input field of every form. On a one-page-site, this leads to scrolling down to the lowest form on the page (usually the contact form). 
Workaround: put setTimeout(function() { window.scrollTo(0,0); }, 100) in the js section of the top page, but this is dirty.
User should be able to select in which field to put an autofocus attribute.

**Comment by perak** [comment]
@christoph2806 fixed and will be available in next version `0.9.74`. I added `autofocus: true/false` property to form object. Kitchen will set `autofocus` attribute to input elements only if this property is set to `true`. Default is `true`.

I hope 0.9.74 will be deployed in next 1-2 days.

**Comment by perak** [comment]
OK, fixed.

CLI version 0.9.74 is deployed now: https://www.meteorkitchen.com/news
