### ISSUE TITLE
Failed upon building aframe example

### ISSUE THREAD

**Issue by rikyperdana** [perak/kitchen-cli#27]
riky@X201E:~/Kitchen$ meteor-kitchen --example-aframe-iss aframe

*** Meteor Kitchen v0.9.73 ***
Source code generator for Meteor.js - www.meteorkitchen.com
Copyright (c) Petar Korponaić
<petar.korponaic@gmail.com>

Reading input file... 
Creating directory structure...
Checking installed packages...
Checking installed packages...
Executing "meteor npm install --save  react react-dom react-mounter react-addons-pure-render-mixin moment aframe aframe-text-component"...
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/home/riky/.meteor/packages/meteor-tool/.1.4.2_3.1hguqum++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/riky/.meteor/packages/meteor-tool/.1.4.2_3.1hguqum++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install" "--save" "" "react" "react-dom" "react-mounter" "react-addons-pure-render-mixin" "moment" "aframe" "aframe-text-component"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF

npm ERR! Refusing to install aframe as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/riky/Kitchen/aframe/npm-debug.log

Error executing "npm". Error executing "meteor". No such file or directory

**Comment by perak** [comment]
@rikyperdana this time something died badly! :D I'll check what is that later...

**Comment by perak** [comment]
@rikyperdana this is fixed (long time ago) so closing this issue.
