### ISSUE TITLE
Emergency: Looks like some default libs are broken

### ISSUE THREAD

**Issue by rikyperdana** [perak/kitchen-cli#28]
I run meteor-kitchen some.json some_dir
But when I run it, it only show >

iron:router
no route definitions found

Looks like some libraries used by meteor-kitchen are broken

**Comment by perak** [comment]
That's a bug in iron:router, see https://github.com/perak/kitchen-site/issues/362

Uploading new version soon

**Comment by perak** [comment]
@rikyperdana please update kitchen-cli to latest `0.9.75`
