### ISSUE TITLE
[v0.9.78] Error during meteor project creation

### ISSUE THREAD

**Issue by bluebackground** [perak/kitchen-cli#29]
Summary: I just tried testing meteor-kitchen and ran the following: 
"meteor-kitchen --example-accounts test-app" 
I'm not sure if I'm doing something wrong or if this this an actually issue.

Result: 
Reading input file... 
Executing "meteor create test-app/"...
You can't create a Meteor project inside another Meteor project.
                                              
Error executing "meteor create test-app/". Error executing "meteor". No such file or directory

**Comment by perak** [comment]
@bluebackground looks like you are typing that inside directory containing meteor application. You cannot do that (not meteor-kitchen limitation - it's meteor limitation).

**Comment by bluebackground** [comment]
@perak I thought that was the problem too. 

I tried running it in a completely different directory, and the result was the same. 
Then, I tried uninstalling and reinstalling. The issue persisted. 

Interestingly, after running the command in a new directory. I found that two hidden files were created:  '.' and '..'

**Comment by bluebackground** [comment]
@perak Solved. There were more hidden files in the surrounding directories.
