### ISSUE TITLE
Generation of React app on Windows breaks ALL imports

### ISSUE THREAD

**Issue by 1jerry** [perak/kitchen-cli#32]
Using Windows 10.  Generated an app using --react option.  It put back-slashes in the **import** statements and is treated as escape sequences instead of path separators.

I believe the _only_ time to use Windows back-slashes are when your are executing Windows commands.

_Always_ use normal slashes in quotes when indicating a folder path, as in **import** statements in JS.

**Comment by perak** [comment]
That was a bug and is fixed now. Thanks for reporting issue. :+1:
