### ISSUE TITLE
Installing it in OS X el capitan is "successful", nothing is really there in the .meteor-kitchen directory. 

### ISSUE THREAD

**Issue by kingmatusevich** [perak/kitchen-cli#7]

**Comment by perak** [comment]
@kingmatusevich I just installed meteor-kitchen with:

```
curl http://www.meteorkitchen.com/install | /bin/sh
```

And everything seems normal. `.meteor-kitchen` directory is not empty (see screenshot).

<img width="1131" alt="screen shot 2016-01-10 at 7 46 38 pm" src="https://cloud.githubusercontent.com/assets/5630814/12223293/2454af60-b7d3-11e5-91ab-10bc31bbe697.png">

How to reproducre your case? Do you have any error messages?

**Comment by kingmatusevich** [comment]
No errors, nothing weird in reproducing. I'll attach the console log. 
[Terminal Saved Output.txt](https://github.com/perak/kitchen-cli/files/86297/Terminal.Saved.Output.txt)

I do have to note, the first I tried installing it was a couple of days ago when in El Cap you got the other El cap bug (https://github.com/perak/kitchen-site/issues/218), and I tried reinstalling after you cleared it in said bug thread, and this new empty directory bug is the one i'm finding.

**Comment by perak** [comment]
@kingmatusevich you're right: after I completely removed kitchen and tried to install it again - I got the same issue.

That's bug in install script.

Fixing...

**Comment by kingmatusevich** [comment]
Thanks! 😊 :+1:

**Comment by perak** [comment]
@kingmatusevich OK, now it's fixed. No, really! :smile:

**Comment by kingmatusevich** [comment]
Working, thank you man! Keep up the good work :+1:
